import { Children } from "react";

const sidebarMenuData = [
     {
          order: 1,
          label: "Analytics",
          path: "/Analytics",
          icon: "mdi:finance",
          view: true,
          add: true,
          edit: true,
          delete: true,
          export: true,
          role_name: "",
          user_id: "",
          children: [
               {
                    label: "Dashboard",
                    path: "/Dashboard",
                    icon: "basil:layout-solid",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    role_name: "",
                    user_id: "",
                    parent: "Analytics",
               //      children: [{
               //           label: "3rd Level dash",
               //           path: "/Bookings",
               //           icon: "basil:lightbulb-alt-solid",
               //           view: true,
               //           add: true,
               //           edit: true,
               //           delete: true,
               //           export: true,
               //           role_name: "",
               //           user_id: "",
               //           parent: "Dashboard",
               //      },
                    
               // ]
               },
               {
                    label: "Pi Coins",
                    icon: "mdi:clipboard-list",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    role_name: "",
                    user_id: "",
                    parent: "Analytics",
                    children: [
                         {
                              label: "Pi Coins Summary",
                              path: "/PicoinsSummaryDashboard",
                              icon: "mdi:clipboard-list",
                              view: true,
                              add: true,
                              edit: true,
                              delete: true,
                              export: true,
                              role_name: "",
                              user_id: "",
                              parent: "Pi Coins",
                         },
                         {
                              label: "Dr/Cr Pi Coins",
                              path: "/DebitCreditPiCoins",
                              icon: "hugeicons:coins-swap",
                              view: true,
                              add: true,
                              edit: true,
                              delete: true,
                              export: true,
                              parent: 'Pi Coins',
                         },
                        

                    ]
               },
              
               // {

               //      label: "Dashboard V2",
               //      path: "/Dashboard-V2",
               //      icon: "basil:layout-solid",
               //      view: true,
               //      add: true,
               //      edit: true,
               //      delete: true,
               //      export: true,
               //      role_name: "",
               //      user_id: "",
               //      parent: "Analytics",
               // },
               // {

               //      label: "New Dashboard",
               //      path: "/NewDashboard",
               //      icon: "mdi:handshake",
               //      view: true,
               //      add: true,
               //      edit: true,
               //      delete: true,
               //      export: true,
               //      role_name: "",
               //      user_id: "",
               // },
               {

                    label: "Partners",
                    icon: "mdi:handshake",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    role_name: "",
                    user_id: "",
                    parent: "Analytics",
                    children: [
                         {
                              label: "STLS Calulations",
                              path: "/PartnerCalculation",
                              icon: "mdi:arrow-right",
                              view: true,
                              add: true,
                              edit: true,
                              delete: true,
                              export: true,
                              role_name: "",
                              user_id: "",
                              parent: "Partners"
                         },
                         {
                              label: "Settlement Slip",
                              path: "/PartnerSettlements",
                              icon: "mdi:arrow-right",
                              view: true,
                              add: true,
                              edit: true,
                              delete: true,
                              export: true,
                              parent: "Partners"
                         },
                         {
                              label: "Payment Config",
                              path: "/PaymentConfig",
                              icon: "mdi:arrow-right",
                              view: true,
                              add: true,
                              edit: true,
                              delete: true,
                              export: true,
                              parent: 'Partners'
                         },
                    ],
               },
               {
                    label: "Account Activity",
                    path: "/MIS",
                    icon: "basil:layout-solid",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    role_name: "",
                    user_id: "",
                    parent: "Analytics",
               }
               
          ],
     },
     // {
     //      order: 2,
     //      label: "Bookings",
     //      path: "/Booking",
     //      icon: "clarity:list-solid-badged",
     //      view: true,
     //      add: true,
     //      edit: true,
     //      delete: true,
     //      export: true,
     //      role_name: "",
     //      user_id: "",
     //      children: [],
     // },
     {
          order: 2,
          label: "Bookings",
          path: "/Bookings",
          icon: "clarity:list-solid-badged",
          view: true,
          add: true,
          edit: true,
          delete: true,
          export: true,
          role_name: "",
          user_id: "",
          children: [

               {
                    label: "Bookings",
                    path: "/Bookings",
                    icon: "clarity:calendar-solid",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    role_name: "",
                    user_id: "",
                    parent: "Bookings",
               },
               {
                    label: "Create Admin Match",
                    path: "/CreateMatch",
                    icon: "mdi:tennis",
                    view: true,    
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Bookings",
               },
               {
                    label: "Bookings Data",
                    path: "/BookingsData",
                    icon: "mdi:table",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Bookings",
               },
               {
                    label: "Cancel and Refund",
                    path: "/CancelandRefund",
                    icon: "mdi:credit-card-refund",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Bookings",
               },

          ],
     },
     // {
     //      order: 3,
     //      label: "Matchmaking",
     //      path: "/matchmaking",
     //      icon: "oui:ml-create-single-metric-job",
     //      view: true,
     //      add: true,
     //      edit: true,
     //      delete: true,
     //      export: true,
     //      role_name: "",
     //      user_id: "",
     //      children: [
     //           {
     //                label: "Metrics",
     //                path: "/MatchmakingMetrics",
     //                icon: "clarity:calendar-solid",
     //                view: true,
     //                add: true,
     //                edit: true,
     //                delete: true,
     //                export: true,
     //                role_name: "",
     //                user_id: "",
     //           },
     //           {
     //                label: "Metrics V2",
     //                path: "/MatchMetrics",
     //                icon: "clarity:calendar-solid",
     //                view: true,
     //                add: true,
     //                edit: true,
     //                delete: true,
     //                export: true,
     //                role_name: "",
     //                user_id: "",
     //           },
     //      ],
     // },
     {
          order: 4,
          label: "Facility",
          path: "/Facility",
          icon: "game-icons:tennis-court",
          view: true,
          add: true,
          edit: true,
          delete: true,
          export: true,
          role_name: "",
          user_id: "",
          children: [
               {
                    label: "Manage Facility",
                    path: "/FacilityManagement",
                    icon: "mdi:event-multiple-check",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Facility",

               },
               {
                    label: "Manage Court",
                    path: "/ManageCourt",
                    icon: "mdi:user-multiple-check",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Facility",
               },
               {
                    label: "Timing & Pricing",
                    path: "/ManageTimePrice",
                    icon: "jam:settings-alt",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Facility",
               },
               {
                    label: "Manage Closing Day",
                    path: "/ManageClosingDay",
                    icon: "ri:calendar-close-fill",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Facility",
               },
               {
                    label: "Dynamic Pricing",
                    path: "/DynamicPricing",
                    icon: "mdi:table-cog",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Facility",
               },
               {
                    label: "Hourly Passes",
                    path: "/HourlyPasses",
                    icon: "mdi:gift-open",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Facility",
               },
               {
                    label: "Hourly Passes List",
                    path: "/HourlyPassesList",
                    icon: "material-symbols:package",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Facility",
               },
               {
                    label: "Membership",
                    path: "/Membership",
                    icon: "material-symbols:card-membership",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Facility",
               },
               {
                    label: "Membership List",
                    path: "/Membershiplist",
                    icon: "eva:list-outline",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Facility",
               }
          ],
     },
     {
          order: 5,
          label: "Events",
          path: "/Events",
          icon: "healthicons:award-trophy",
          view: true,
          add: true,
          edit: true,
          delete: true,
          export: true,
          role_name: "",
          user_id: "",
          children: [
               {
                    label: "Manage Events",
                    path: "/ManageEvents",
                    icon: "mdi:event-multiple-check",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Events",

               },
               {
                    label: "Manage UGTs",
                    path: "/ManageUGTs",
                    icon: "mdi:account-box-edit-outline",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Events",
               },
               {
                    label: "Manage Venues",
                    path: "/EventVenue",
                    icon: "mdi:office-building-location",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Events",

               },
               {
                    label: "Event Registrations",
                    path: "/RegisteredUsers",
                    icon: "mdi:user-multiple-check",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Events",

               },
               {
                    label: "Event Unregistration",
                    path: "/UnregisteredUsers",
                    icon: "mdi:account-off",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Events",
               },
               {
                    label: "Event Organizers",
                    path: "/Organizer",
                    icon: "flowbite:users-group-solid",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Events",
               },
               // {
               //      label: "Event Refund",
               //      path: "/EventCancelandRefund",
               //      icon: "mdi:sack",
               //      view: true,
               //      add: true,
               //      edit: true,
               //      delete: true,
               //      export: true,
               //      parent: "Events",
               // },
               // Add more submenus as needed
          ],


     },
     {
          order: 6,
          label: "Coupons",
          path: "/Coupons",
          icon: "mdi:coupon",
          view: true,
          add: true,
          edit: true,
          delete: true,
          export: true,
          role_name: "",
          user_id: "",
          children: [],
     },
     {
          order: 7,
          label: "Coaching",
          path: "/Coaches",
          icon: "map:tennis",
          view: true,
          add: true,
          edit: true,
          delete: true,
          export: true,
          role_name: "",
          user_id: "",
          children: [
               {
                    label: "Coaches",
                    path: "/Coaches",
                    icon: "map:tennis",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    parent: "Coaching"
               },
               {
                    label: "Coaching Programs",
                    path: "/CoachingProgram",
                    icon: "mdi:table-tennis",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Coaching"
               },
               {
                    label: "Coaching Sessions",
                    path: "/CoachingSessions",
                    icon: "mdi:timeline-clock",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Coaching"
               },
               {
                    label: "Coaches Approval",
                    path: "/CoachesApproval",
                    icon: "mdi:approve",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: "Coaching"
               },
          ]
     },

     // {
     //      order: 10,
     //      label: "Pi Coins",
     //      path: "/PiCoins",
     //      icon: "pepicons-pencil:coins-circle-filled",
     //      view: true,
     //      add: true,
     //      edit: true,
     //      delete: true,
     //      export: true,
     //      role_name: "",
     //      user_id: "",
     //      children: [
     //           {
     //                label: "Debit/Credit Pi Coins",
     //                path: "/DebitCreditPiCoins",
     //                icon: "hugeicons:coins-swap",
     //                view: true,
     //                add: true,
     //                edit: true,
     //                delete: true,
     //                export: true,
     //                parent: 'Settings'
     //           },]
     // },
     {
          order: 8,
          label: "Settings",
          path: "/Settings",
          icon: "material-symbols:settings",
          view: true,
          add: true,
          edit: true,
          delete: true,
          export: true,
          role_name: "",
          user_id: "",
          children: [
               {
                    label: "Chat",
                    path: "/Chat",
                    icon: "ph:chat-teardrop-text-fill",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: 'Settings'
               },
               {
                    label: "Configs",
                    path: "/Configs",
                    icon: "file-icons:config-go",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: 'Settings'
               },
               {
                    label: "Registered Users",
                    path: "/RegisteredUser",
                    icon: "flowbite:users-solid",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: 'Settings'
               },
               {
                    label: "Skill Levels",
                    path: "/SkillLevels",
                    icon: "game-icons:podium-winner",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: 'Settings'
               },
               {
                    label: "Manage Roles",
                    path: "/ManageRoles",
                    icon: "ic:round-manage-accounts",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: 'Settings'
               },
               {
                    label: "Admin Users",
                    path: "/AdminUsers",
                    icon: "clarity:assign-user-solid",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: 'Settings'
               },

               {
                    label: "App Notification",
                    path: "/AppNotification",
                    icon: "ion:notifications",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: 'Settings'
               },
               {
                    label: "Promotions",
                    path: "/Promotions",
                    icon: "bxs:offer",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: 'Settings'
               },
               {
                    label: "Banners",
                    path: "/Banners",
                    icon: "ri:image-fill",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: 'Settings'
               },
               {
                    label: "Tutorial Videos",
                    path: "/TutorialVideos",
                    icon: "ri:youtube-fill",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: 'Settings'
               },
               {
                    label: "How To",
                    path: "/HowTo",
                    icon: "mdi:help-circle",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: 'Settings'
               },
               // {
               //      label: "Payment Config",
               //      path: "/PaymentConfig",
               //      icon: "fluent:payment-16-filled",
               //      view: true,
               //      add: true,
               //      edit: true,
               //      delete: true,
               //      export: true,
               //      parent: 'Settings'
               // },
               // {
               //      label: "User Skill Levels",
               //      path: "/SkillLevel",
               //      icon: "fluent:payment-16-filled",
               //      view: true,
               //      add: true,
               //      edit: true,
               //      delete: true,
               //      export: true,
               //      parent: 'Settings'
               // },
               {
                    label: "User Skill Levels",
                    path: "/SkillLevel",
                    icon: "carbon:skill-level-advanced",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: 'Settings'
               },

               {
                    label: "Event Flyers",
                    path: "/EventFlyers",
                    icon: "ic:round-event",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: 'Settings'
               },
               {
                    label: "Homepage Tiles",
                    path: "/HomePageTiles",
                    icon: "fluent-mdl2:tiles",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: 'Settings'
               },
               {
                    label: "List Of Transactions",
                    path: "/PaymentView",
                    icon: "mdi:bank-transfer",
                    view: true,
                    add: true,
                    edit: true,
                    delete: true,
                    export: true,
                    parent: 'Settings'
               },
               // {
               //      label: "Debit/Credit Pi Coins",
               //      path: "/DebitCreditPiCoins",
               //      icon: "hugeicons:coins-swap",
               //      view: true,
               //      add: true,
               //      edit: true,
               //      delete: true,
               //      export: true,
               //      parent: 'Settings'
               // },
               // {
               //      label: "Platform Charges",
               //      path: "/PlatformCharges",
               //      icon: "mdi:percent",
               //      view: true,
               //      add: true,
               //      edit: true,
               //      delete: true,
               //      export: true,
               //      parent: "Settings",
               // }

               // Add more submenus as needed

          ],
     },
]

export default sidebarMenuData;